### ISSUE TITLE
Html Forms 

### ISSUE THREAD

**Issue by siddhi-244** [HackClubRAIT/Frontend-Owls#1]
### Description 
Add a file Html_Forms.md in html folder

### Doc Domain

- [x] Html
- [ ] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

Hacktoberfest 
<hr/>

**Comment by iatharva** [comment]
Can I take up this issue and do it?

**Comment by siddhi-244** [comment]
> Can I take up this issue and do it?

Sure. I will assign it to you. Happy contributing 🎊🎊

**Comment by iatharva** [comment]
Thanks
