### ISSUE TITLE
heading or h tag in HTML

### ISSUE THREAD

**Issue by iatharva** [HackClubRAIT/Frontend-Owls#10]
### Description of  the change
Describing heading or h tag in HTML by adding a new file as `Html_headings.md`

### Domain of Docs

- [x] HTML
- [ ] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program?
hacktoberfest 

<hr/>

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.

**Comment by iatharva** [comment]
Thanks
