### ISSUE TITLE
CSS Box Model

### ISSUE THREAD

**Issue by dickyrex19** [HackClubRAIT/Frontend-Owls#11]
### Description 
Describing CSS box model

### Doc Domain
- [ ] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
hacktoberfest
<hr/>

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.
