### ISSUE TITLE
CSS Flexbox

### ISSUE THREAD

**Issue by artimanputra** [HackClubRAIT/Frontend-Owls#12]
### Description 
CSS Flexbox

### Doc Domain

- [ ] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program?

Hacktoberfest
<hr/>

**Comment by siddhi-244** [comment]
Assigning this to you. Make sure you refer the merged prs.🎊🎊🎊

**Comment by artimanputra** [comment]
> Assigning this to you. Make sure you refer the merged prs.🎊🎊🎊

Is I have to create CSSFlexbox.md file? Which contains documentation of CSS flexbox.

**Comment by siddhi-244** [comment]
> > Assigning this to you. Make sure you refer the merged prs.🎊🎊🎊
> 
> Is I have to create CSSFlexbox.md file? Which contains documentation of CSS flexbox.

Yes
