### ISSUE TITLE
Animated Glowing Button using HTML & CSS

### ISSUE THREAD

**Issue by arkayyy** [HackClubRAIT/Frontend-Owls#22]
### Description 
I would like to add a tutorial cum documentation for creating a stylish glowing animated button using just HTML and CSS, which can be implemented in almost any project.

### Doc Domain

- [x] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program?
Hacktoberfest 2021

<hr/>

**Comment by siddhi-244** [comment]
It's a documentation project uh can add ur design here 
https://github.com/siddhi-244/Embellish

**Comment by girija0707** [comment]
> It's a documentation project uh can add ur design here https://github.com/siddhi-244/Embellish

Yes you can contribute to the above repository,even that's under hacktober fest
