### ISSUE TITLE
Add documentation for glassmorphism using html and css

### ISSUE THREAD

**Issue by itsme-aparna** [HackClubRAIT/Frontend-Owls#23]
### Description 
I would like to make a tutorial for a responsive and elegant glassmorphism card using only html and css.

### Doc Domain

- [x] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
Hacktoberfest 2021

<hr/>

**Comment by itsme-aparna** [comment]
@girija0707 @siddhi-244 please assign this to me under hacktoberfest 2021.

**Comment by girija0707** [comment]
> @girija0707 @siddhi-244 please assign this to me under hacktoberfest 2021.

Make sure you do the documentation in .md file

**Comment by itsme-aparna** [comment]
@girija0707 I have created the documentation in .md file. Kindly review and accept my PR.
