### ISSUE TITLE
Responsive Animated Search Bar using HTML & CSS

### ISSUE THREAD

**Issue by arkayyy** [HackClubRAIT/Frontend-Owls#24]
### Description 
I would like to add a tutorial cum documentation for building a responsive and animated search bar using only HTML and CSS.

### Doc Domain

- [x] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

Hacktoberfest 2021
<hr/>

**Comment by arkayyy** [comment]
@siddhi-244 Please consider assigning me this issue under Hacktoberfest tag.

**Comment by siddhi-244** [comment]
> ### Description
> I would like to add a tutorial cum documentation for building a responsive and animated search bar using only HTML and CSS.
> 
> ### Doc Domain
> * [x]  Html
> * [x]  CSS
> * [ ]  JavaScript
> * [ ]  Bootstrap
> 
> #### Are you contributing under any open-source program ?
> Hacktoberfest 2021

It's a documentation project. You can contribute your design here https://github.com/siddhi-244/Embellish

**Comment by arkayyy** [comment]
> > @siddhi-244 Please consider assigning me this issue under Hacktoberfest tag.
> 
> You want to add documentation about it?

@siddhi-244 No, I have actually put up a pull request for this animated search bar in Embellish repository. Kindly review and accept. Thank you
