### ISSUE TITLE
CSS display property.

### ISSUE THREAD

**Issue by Pranavanbu28** [HackClubRAIT/Frontend-Owls#3]
### Description 
This issue will describe about the CSS display property and explain about its types.
### Doc Domain

- [ ] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
Hacktoberfest participant

<hr/>

**Comment by Pranavanbu28** [comment]
Hi I would like to work on this issue. Can you please assign this issue to me?

**Comment by siddhi-244** [comment]
Ok . Inside Css folder add a file Display_Properties.md and explain about display properties. Assigning this to you !🎊🎊🎊

**Comment by Pranavanbu28** [comment]
Thanks!!
