### ISSUE TITLE
Animate On Scroll Library

### ISSUE THREAD

**Issue by HardikSJain** [HackClubRAIT/Frontend-Owls#30]
### Description 
Animate On Scroll Library doc
Animations are used to attract people’s attention and add interactivity to your web application rather than just a static page. With animations, users tend to engage more with the features of your application. One of the best animations to add to your webpage is the on-scroll animation. An on-scroll animation is a form of Scrollytelling, which means telling a story or displaying content while scrolling.
### Doc Domain

- [x] Html
- [x] CSS
- [x] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
hacktoberfest

<hr/>

**Comment by girija0707** [comment]
please describe doc type

**Comment by HardikSJain** [comment]
It'll contain css and js for installing the library in the vue app, and the initializing part will be done in html.

**Comment by HardikSJain** [comment]
may i get to work on it ??
