### ISSUE TITLE
HTML Block and Inline Elements

### ISSUE THREAD

**Issue by kar-cloud** [HackClubRAIT/Frontend-Owls#32]
### Description 
Describe more about the issue.

### Doc Domain

- [ ] Html
- [ ] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
hacktoberfest

<hr/>

**Comment by kar-cloud** [comment]
I want to work on this issue.

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🔥
