### ISSUE TITLE
List in HTML

### ISSUE THREAD

**Issue by girija0707** [HackClubRAIT/Frontend-Owls#4]
### Description 
Explain list in HTML, add that file in HTML folder

### Doc Domain

- [x] Html
- [ ] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Akshadaworlikar** [comment]
please assign this task to me?

**Comment by girija0707** [comment]
> please assign this task to me?

yeep go ahead with this

**Comment by girija0707** [comment]
any updates @Akshadaworlikar
