### ISSUE TITLE
Types of CSS

### ISSUE THREAD

**Issue by utkarsh006** [HackClubRAIT/Frontend-Owls#52]
### Description 
Types of CSS : Internal, External and Inline

### Doc Domain

- [ ] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
Hackclub RAIT

<hr/>

**Comment by pooja-sanap-53** [comment]
@purva2906 Can you assign me this issue? I can fix till tomorrow.

**Comment by pooja-sanap-53** [comment]
I am contributing under HSOC22.

**Comment by GundaSudarrshan** [comment]
@purva2906 You can assign me this issue!!!

**Comment by piyush-sri** [comment]
I am willing to contribute by adding an in depth explanation about Types of Css and how to use them, I am working as a Faculty guiding students in the subject of web designing and publishing. I would love to contribute to your project ,
Thank you!

**Comment by girija0707** [comment]
> I am willing to contribute by adding an in depth explanation about Types of Css and how to use them, I am working as a Faculty guiding students in the subject of web designing and publishing. I would love to contribute to your project , Thank you!

Heey you can create your own issues and we'll assign it to you. create issues on topics whose documentation does not exist in the repo and is necessary
