### ISSUE TITLE
Bootstrap Carousel

### ISSUE THREAD

**Issue by purva2906** [HackClubRAIT/Frontend-Owls#54]
### Description 
Add the documentation for bootstrap carousel.

### Doc Domain

- [ ] Html
- [ ] CSS
- [ ] JavaScript
- [x] Bootstrap

#### Are you contributing under any open-source program ?

Hackclub Summer Of Code
<hr/>

**Comment by girija0707** [comment]
> @purva2906 can I contribute to this issue under HSOCC22.

Congratulations 🎉🎉you can start working on this make sure to add originality to the documentation we'll check for plagiarism
