### ISSUE TITLE
JavaScript Operators

### ISSUE THREAD

**Issue by purva2906** [HackClubRAIT/Frontend-Owls#55]
### Description 
Write about the JavaScript Operators in detail.

### Doc Domain

- [ ] Html
- [ ] CSS
- [x] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

Hackclub Summer of code
<hr/>

**Comment by GundaSudarrshan** [comment]
@purva2906  can you assign me this issue

**Comment by girija0707** [comment]
> @purva2906 Please assign this to me.

You can start working on it 🎉
