### ISSUE TITLE
Css Gradients

### ISSUE THREAD

**Issue by purva2906** [HackClubRAIT/Frontend-Owls#57]
### Description 
Add documentation about gradients in css.

### Doc Domain

- [ ] Html
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

Hackclub Rait Soc
<hr/>

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSSOC

**Comment by GundaSudarrshan** [comment]
@tanya-gupta25  Can You pls Assign me this Issue

**Comment by girija0707** [comment]
> I want to work on this issue under HSOC

Congratulations 🎉🎉 you can start working on it. Make sure to add originality we'll also check for plagiarism

**Comment by girija0707** [comment]
> @tanya-gupta25 Can You pls Assign me this Issue

Hey you can try for some other issues also make sure to tag me or @purva2906 since we are the project admins and we'll be assigning and merging the requests

**Comment by girija0707** [comment]
@GundaSudarrshan hey you can try commenting on other issues or creating your own just make sure to tag me or @purva2906 since we are the project Admins and will be assigning the issues

**Comment by girija0707** [comment]
@tanya-gupta25 how long would it take for you please let us know else we would have to un assign you and assign this task to someone else

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 how long would it take for you please let us know else we would have to un assign you and assign this task to someone else

Extremely Sorry for the delay I'll surely make a PR by tomorrow evening

**Comment by girija0707** [comment]
> > @tanya-gupta25 how long would it take for you please let us know else we would have to un assign you and assign this task to someone else
> 
> Extremely Sorry for the delay I'll surely make a PR by tomorrow evening

No problem do let us know if you face any difficulties
