### ISSUE TITLE
Bootstrap Forms

### ISSUE THREAD

**Issue by purva2906** [HackClubRAIT/Frontend-Owls#58]
### Description 
Add documentation about forms in bootstrap.

### Doc Domain

- [ ] Html
- [ ] CSS
- [ ] JavaScript
- [x] Bootstrap

#### Are you contributing under any open-source program ?

Hackclub Summer of Code
<hr/>

**Comment by vickyrules** [comment]
@purva2906 please, assign this to me.

**Comment by iamsandeepshekhawat** [comment]
@purva2906 Please assign this issue to me.

**Comment by girija0707** [comment]
> @purva2906 please, assign this to me.

Congratulations 🎉 you can start working on this

**Comment by girija0707** [comment]
> @purva2906 Please assign this issue to me.

Hey you can comment on other issues or create your own
