### ISSUE TITLE
CSS TABLE STYLING

### ISSUE THREAD

**Issue by deepshikha2708** [HackClubRAIT/Frontend-Owls#64]
### Description of  the change
Describe more about the change.

### Domain of Docs

- [ ] HTML
- [x] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

<hr/>

**Comment by deepshikha2708** [comment]
can you assign me this issue please @girija0707 ??

**Comment by deepshikha2708** [comment]
done ig

**Comment by purva2906** [comment]
Assigning

**Comment by girija0707** [comment]
@deepshikha2708 do let us know if you face any issue hope you have started working on the PR

**Comment by deepshikha2708** [comment]
I should create a different file for it right?
