### ISSUE TITLE
Bootstrap Flex

### ISSUE THREAD

**Issue by ashmeet-chhabra** [HackClubRAIT/Frontend-Owls#66]
### Description 
- Describe what a flexbox is and how to create one in Bootstrap
- Document the different classes and how they manage layout
- Include responsive Bootstrap utilities

### Doc Domain

- [ ] Html
- [ ] CSS
- [ ] JavaScript
- [x] Bootstrap

#### Are you contributing under any open-source program ?

Yes, I am contributing under HSOC22

<hr/>

**Comment by purva2906** [comment]
Assigned

**Comment by girija0707** [comment]
@ashmeet-chhabra do let us know if you are facing any issue , in case of inactivity we'll have to assign this issue to someone else

**Comment by ashmeet-chhabra** [comment]
> @ashmeet-chhabra do let us know if you are facing any issue , in case of inactivity we'll have to assign this issue to someone else

Hey! I'm so sorry for the delay, but I'll just need some extra time. I'll complete it by tomorrow if that's alright with you

**Comment by girija0707** [comment]
> > @ashmeet-chhabra do let us know if you are facing any issue , in case of inactivity we'll have to assign this issue to someone else
> 
> Hey! I'm so sorry for the delay, but I'll just need some extra time. I'll complete it by tomorrow if that's alright with you

Ok no problem

**Comment by girija0707** [comment]
Hey @ashmeet-chhabra work on your issue by tomorrow else we'll have to close the issue
