### ISSUE TITLE
JavaScript Functions

### ISSUE THREAD

**Issue by deepshikha2708** [HackClubRAIT/Frontend-Owls#69]
### Description 
Adding another file describing the JavaScript Functions.

### Doc Domain

- [ ] Html
- [ ] CSS
- [x] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?

<hr/>

**Comment by deepshikha2708** [comment]
@girija0707 @purva2906 can you assign me this issue?

**Comment by girija0707** [comment]
Congratulations you can start working @deepshikha2708

**Comment by girija0707** [comment]
@deepshikha2708 can you let us know of the further developments

**Comment by deepshikha2708** [comment]
can i get a day more please?

**Comment by deepshikha2708** [comment]
I am extremely sorry by mistake I created pull request for an empty file. Can do this again?
