### ISSUE TITLE
Media in HTML 

### ISSUE THREAD

**Issue by kshitija-2001** [HackClubRAIT/Frontend-Owls#7]
### Description 
Describing Media tags in HTML

### Doc Domain

- [ ] Html
- [ ] CSS
- [ ] JavaScript
- [ ] Bootstrap

#### Are you contributing under any open-source program ?
Hacktoberfest

<hr/>

**Comment by dickyrex19** [comment]
can you assign me to this issue ?

**Comment by siddhi-244** [comment]
> ### Description
> Describing Media tags in HTML
> 
> ### Doc Domain
> * [ ]  Html
> * [ ]  CSS
> * [ ]  JavaScript
> * [ ]  Bootstrap
> 
> #### Are you contributing under any open-source program ?
> Hacktoberfest

Assigning this to you🎊🎊🎊🎊. This is a documentation project.  Please refer to merged prs.

**Comment by kshitija-2001** [comment]
Thank you!
